#!/usr/bin/python3

import hashlib

file = open('input')
inp = file.read()
file.close()

#Try every number from zero
num = 0
password = ''
while(len(password) < 8):
    attempt = inp + str(num)
    hash = hashlib.md5(attempt.encode())
    #Check for leading 0's
    if(hash.hexdigest().startswith("00000")):
        password += str(hash.hexdigest()[5])
    num += 1

print(password)