#!/usr/bin/python3

#Get complete list
file = open('input')
inp = file.readlines()
file.close()

#Get Definite properties
file = open('TickerTape')
tt = file.readlines()
file.close()

#Parse TickerTape
specprop = {}
for p in tt:
    p = p.split(': ')
    specprop[p[0]] = int(p[1].strip())

#Iterate through aunts
for p in inp:
    tempdict = {}
    p = p.split()
    tempdict[p[2][:-1]] = int(p[3].strip()[:-1])
    tempdict[p[4][:-1]] = int(p[5].strip()[:-1])
    tempdict[p[6][:-1]] = int(p[7].strip())
    #compare aunt
    simcount = 0
    for s in specprop:
        #If sure compare items, else add 1 to similarity count
        if not tempdict.get(s) == None:
            if tempdict[s] == specprop[s]:
                simcount +=1
        else:
            simcount += 1

    #Count of 10 is a perfect score
    if simcount > 9:
        print(f'{p[0]} {p[1]} {simcount}')
