#!/usr/bin/python3

file = open('input')
inp = file.readlines()
file.close()

#Correct Triangles
count = 0

for p in inp:
    #sort numbers
    p = list(map(int, p.split()))
    p.sort()
    #Check for valid triangle
    if p[0] + p[1] > p[2]:
        count += 1

#Print number of correct triangles
print(count)
