#!/usr/bin/python3

file = open('input')
inp = file.read().split("\n")
file.close()

start = [0,0]
dir = 1

for p in inp:
    if(p[0] == "N"):
        start[1] += int(p[1:])
        pass
    if(p[0] == "E"):
        start[0] += int(p[1:])
        pass
    if(p[0] == "S"):
        start[1] -= int(p[1:])
        pass
    if(p[0] == "W"):
        start[0] -= int(p[1:])
        pass
    if(p[0] == "F"):
        if(dir == 0):
            start[1] += int(p[1:])
            pass
        if(dir == 1):
            start[0] += int(p[1:])
            pass
        if(dir == 2):
            start[1] -= int(p[1:])
            pass
        if(dir == 3):
            start[0] -= int(p[1:])
            pass
        pass
    if(p[0] == "L"):
        dir -= int(p[1:])/90
        if(dir < 0):
            dir = 4+dir
        pass
    if(p[0] == "R"):
        dir += int(p[1:])/90
        if(dir > 3):
            dir = dir - 4
        pass

print(abs(start[0])+abs(start[1]))