#!/usr/bin/python3

#Read input
file = open('input')
inp = file.readlines()
file.close()

#Init Reindeer data. Name, speed, endurance, rest,total dist, points
reindeer = {}

for p in inp:
    p = p.split(" ")
    reindeer[p[0]] = [int(p[3]),int(p[6]),int(p[13]), 0, 0]

#Init time
time = 2503

#Check distance every second
for p in range(time):
    for s in reindeer:
        #Helpful Variables
        cycletime = reindeer[s][1] + reindeer[s][2]
        speed = reindeer[s][0]
        runtime = reindeer[s][1]
        #If running increase distance
        if p%cycletime  < runtime:
            reindeer[s][3] += speed
    #Assess distance
    #Determine max
    farthest = 0
    for s in reindeer:
        if reindeer[s][3] > farthest:
            farthest = reindeer[s][3]
    #Reward points
    for s in reindeer:
        if reindeer[s][3] == farthest:
            reindeer[s][4] += 1

#Determine winner
maxpts = 0
for s in reindeer:
    if reindeer[s][4] > maxpts:
        maxpts = reindeer[s][4]

print(maxpts)
