#!/usr/bin/python3

file = open('input')
inp = file.read().split("\n")
file.close()

#useful variables
down = 1
right = 3
layer = 0

count = 0
#Go until bottom
while(layer < len(inp)):
    #Check position
    if(inp[layer][(layer * right) % len(inp[0])] == "#"):
        count += 1
    #Inc layer
    layer += down
print(count)