#!/usr/bin/python3

file = open('input')
inp = file.read().split("\n")
file.close()

#useful variables (Right, Down)
slopes = [(1,1),(3,1),(5,1),(7,1),(1,2)]

total = 1
for p in slopes:
    count = 0
    row = 0
    column = 0
    #Go until bottom
    while(row < len(inp)):
        #Check position
        if(inp[row][column % len(inp[0])] == "#"):
            count += 1
        #Inc row/column
        column += p[0]
        row += p[1]
    print(count)
    total *= count
print(total)