#!/usr/bin/python3

file = open('input')
inp = file.read().split('\n')
file.close()

#Init sum
sum = 0

#For every line
for p in inp:
    p = int(p)
    #Divide, round down, subtract 2
    p = p//3
    p -= 2
    sum += p

#Print solution
print(sum)