#!/usr/bin/python3

import re

file = open('input')
inp = file.read().split("\n\n")
file.close()

#cid (Country ID) optional don't care

fields = ["byr", "iyr", "eyr", "hgt", "hcl", "ecl", "pid"]

count = 0
for p in inp:
    p = p.replace("\n", " ").split(" ")
    fielddict = {}
    for s in p:
        fielddict[s.split(":")[0]] = s.split(":")[1]
    #validcount
    vcount = 0
    #check for fields
    for s in fields:
        if s == "byr":
            if(not(int(fielddict.get(s, -1)) >= 1920 and int(fielddict.get(s, -1)) <= 2002)):
                continue
        if s == "iyr":
            if(not(int(fielddict.get(s, -1)) >= 2010 and int(fielddict.get(s, -1)) <= 2020)):
                continue
        if s == "eyr":
            if(not(int(fielddict.get(s, -1)) >= 2020 and int(fielddict.get(s, -1)) <= 2030)):
                continue
        if s == "hgt":
            if(not("cm" in fielddict.get(s, "-1") or "in" in fielddict.get(s, "-1"))):
                continue
            if("cm" in fielddict.get(s, "-1")):
                fielddict[s] = fielddict[s].replace("cm", "")
                if(not(int(fielddict.get(s, -1)) >= 150 and int(fielddict.get(s, -1)) <= 193)):
                    continue
            if("in" in fielddict.get(s, "-1")):
                fielddict[s] = fielddict[s].replace("in", "")
                if(not(int(fielddict.get(s, -1)) >= 59 and int(fielddict.get(s, -1)) <= 76)):
                    continue
        if s == "hcl":
            if(not(re.search("^#[a-f0-9]{6}$", fielddict.get(s,"-1")))):
                continue
        if s == "ecl":
            if(not(fielddict.get(s, -1) in ("amb", "blu", "brn", "gry", "grn", "hzl","oth"))):
                continue
        if s == "pid":
            if(not(re.search("[0-9]{9}", fielddict.get(s, "-1")))):
                continue
        vcount += 1
    #ensure all fields exist
    if vcount == len(fields):
        count += 1
print(count)