#!/usr/bin/python3

#Notes
# 1 => 10 - 10
# 2 => 30 - 10 - 20
# 3 => 40 - 10 - 30
# 4 => 70 - 10 - 20 - 40
# 5 => 60 - 10 - 50
# 6 => 120 - 10 - 20 - 30 - 60
# 7 => 80 - 10 - 70
# 8 => 150 - 10 - 20 - 40 - 80
# 9 => 130 - 10 - 30 - 90
#10 => 180 - 10 - 20 - 50 - 100
#180 => 17,10

#Find every unique combination of numbers that add to input
#and
#That contain all multiples of all numbers in the list
file = open('input')
inp = file.read()
file.close()

#Divide by 10 to simplify
inp = int(int(inp)/10)
#We know that 1 is always a factor
tmp = inp - 1

while True:
    factors = []

