#!/usr/bin/python3

import math

file = open('input')
inp = file.read()
file.close()

inp = int(int(inp)/10)
for p in range(1, inp):
    #Used an optimization for finding prime numbers from u/roboticon on reddit.
    #This method is WAY faster than running a while loop looking for divisors.
    small_divisors = [i for i in range(1, int(math.sqrt(p)) + 1) if p % i == 0]
    large_divisors = [p / d for d in small_divisors if p != d * d]
    divisors = small_divisors + large_divisors
    if sum(divisors) >= inp:
        print(f"House:{p}, Presents:{sum(divisors)}")
        break