#!/usr/bin/python3

import math

file = open('input')
inp = file.readlines()
file.close()

reg = {'a':0, 'b':0}
pointer = 0;

while 0 <= pointer < len(inp):
    print(f"pointer: {pointer}, a:{reg['a']}")
    line = inp[pointer].strip().split(' ')
    if(line[0] == 'hlf'):
        reg[line[1]] = math.floor(reg[line[1]]/2)
        pointer += 1
        continue
    if line[0] == 'tpl':
        reg[line[1]] = int(reg[line[1]]*3)
        pointer += 1
        continue
    if line[0] == 'inc':
        reg[line[1]] += 1
        pointer += 1
        continue
    if line[0] == 'jmp':
        pointer += int(line[1])
        continue
    if line[0] == 'jie':
        if reg[line[1][:1]] % 2 == 0:
            pointer += int(line[2])
        else:
            pointer += 1
        continue
    if line[0] == 'jio':
        if reg[line[1][:1]] == 1:
            pointer += int(line[2])
        else:
            pointer += 1
        continue

print(reg)