#!/usr/bin/python3

import re

file = open('input')
inp = file.readlines()
file.close()

#A godly regex statement, because I AM A WIZARD.
rule = re.compile(r'(^(([a-zA-Z])|(\[[a-zA-Z]*\]))*(.)(.)\5(([a-zA-Z])|(\[[a-zA-Z]*\]))*\[[a-zA-Z]*\6\5\6[a-zA-Z]*\](([a-zA-Z])|(\[[a-zA-Z]*\]))*$)|(^(([a-zA-Z])|(\[[a-zA-Z]*\]))*\[[a-zA-Z]*(.)(.)\17[a-zA-Z]*\](([a-zA-Z])|(\[[a-zA-Z]*\]))*\18\17\18(([a-zA-Z])|(\[[a-zA-Z]*\]))*$)')
#Counter
support = 0

#for each IPv7
for p in inp:
    p = p.strip()
    if re.search(rule, p):
        dup = re.findall(rule, p)[0]
        #Weed out duplicates
        if not (dup[4] == dup[5] and dup[16] == dup[17]):
            support += 1
#Print result
print(support)