#!/usr/bin/python3

import re

file = open('input')
inp = file.read().split("\n")
file.close()

dict = {}
ing = set()
alg = set()

for p in inp:
    p = p.split(" (contains")
    for s in p[0].split(" "):
        ing.add(s)
        for t in p[1][:-1].split(','):
            temp = dict.get(t.strip(), {})
            ptemp = temp.get(s.strip(), 0)+1
            temp[s.strip()] = ptemp
            dict[t.strip()] = temp

for p in dict:
    max_value = max(dict[p].values())
    itemalg = [(p,k) for k,v in dict[p].items() if v == max_value]
    for s in itemalg:
        alg.add(s)

v = list(alg)
v.sort()
print(v)
##Open a text editor and brute force that nonsense