#!/usr/bin/python3

import itertools

file = open('input')
inp = file.readlines()
file.close()

#Total egg nog
nog = 150

#Init container values
containers = []
for p in inp:
    containers.append(int(p))
containers.sort(reverse = True)

#View all combinations
comb = []
for p in range(1,len(containers) + 1):
    comb.append(list(itertools.combinations(containers,p)))

#Check combinations least containers
small = -1
for p in comb:
    for s in p:
        if sum(s) == nog and small == -1 or len(s) < small:
            small = len(s)

#Find ways to use the least amount of containers
count = 0
for p in comb:
    for s in p:
        if sum(s) == nog and len(s) == small:
            count += 1

print(count)
